project:
  type: book

execute: 
  freeze: auto

book:
  title: Einführung in die Datenwissenschaft mit R
  author: 
  - family: Glahn
    given: Christian  
  page-navigation: true

  repo-url: https://github.com/dxiai/dxi-r
  repo-actions: 
  - issue

  chapters:
  - index.qmd
  # - vorwort.qmd
 
  - kapitel/einleitung/kapitel.md
  # - kapitel/tool-chain/kapitel.md

  - part: "Teil I: Datenquellen"
    chapters:
    - kapitel/daten-einlesen/kapitel.md
    - kapitel/datentypen/kapitel.md
    - kapitel/zeichenketten/kapitel.md
    - kapitel/datenstrukturen/kapitel.md
    # - kapitel/externe-datenquellen/kapitel.md
 
  - part: "Teil II: Mathematik der Daten"
    chapters:
    - kapitel/variablen/kapitel.md
    - kapitel/datenströme/kapitel.md
    - kapitel/funktionen/kapitel.md
    - kapitel/boolsche-operationen/kapitel.md
    - kapitel/vektor-operationen/kapitel.md
    - kapitel/matrix-operationen/kapitel.md
  
  - part: "Teil III: Deskriptive Datenanalyse"
    chapters:
    - kapitel/daten-formen/kapitel.md
    - kapitel/daten-beschreiben/kapitel.md
    - kapitel/daten-visualisieren/kapitel.md
    - kapitel/lineare-modelle/kapitel.md
    
  - references.qmd

format:
  html:
    theme: bootstrap
    toc: true
    html-math-method: katex

csl: _contrib/apa.csl